name: E2E iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v4
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build-${{ hashFiles('ios/**/*') }}
          restore-keys: |
            ${{ runner.os }}-detox-build-

      - name: Detox build
        run: yarn detox build --configuration ios.sim.debug

      - name: Detox test
        run: yarn detox test --configuration ios.sim.debug e2e/continueButton.test.js --cleanup --headless --record-logs all

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: artifacts/
