name: Detox iOS Tests

on:
  workflow_dispatch:

jobs:
  detox-ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install Detox CLI
        run: yarn global add detox-cli

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Install AppleSimUtils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Detox rebuild framework cache
        run: yarn detox rebuild-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-detox-build-

      - name: Start Metro bundler in background
        run: yarn start &
        env:
          CI: true

      - name: Wait for Metro to start
        run: |
          timeout 30s bash -c "until curl -s http://localhost:8081/status; do sleep 1; done"
          echo "Metro is up and running"

      - name: Detox build
        run: yarn detox build --configuration ios.sim.debug

      - name: Run Detox tests
        run: detox test --configuration ios.sim.debug --loglevel verbose e2e/continueButton.test.js
        env:
          CI: true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: artifacts
