name: Run Detox iOS Tests
on:
  workflow_dispatch:

jobs:
  detox-ios:
    name: iOS - Build and run Detox tests
    runs-on: macos-13-xlarge

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: Install Dependencies
        run: npm install

      - name: Install CocoaPods Dependencies
        run: cd ios && pod install

      - name: Build Detox for iOS
        run: npm run detox:ios:build

      - name: Start Metro Server
        run: npm run detox:start &

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox Tests on iOS
        run: npm detox test --configuration ios.sim.debug e2e/continueButton.test.js --cleanup --headless --record-logs all

      - name: Upload Test Artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-ios-artifacts
          path: artifacts
          retention-days: 5
