name: Detox iOS Tests

on:
  workflow_dispatch:

jobs:
  detox-ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
        env:
          XCODE_VERSION: 16.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Detox CLI
        run: yarn global add detox-cli

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Install AppleSimUtils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Cache Detox framework
        id: cache-detox-framework
        uses: actions/cache@v3
        with:
          path: ~/Library/Detox
          key: ${{ runner.os }}-detox-framework-${{ hashFiles('package.json', 'yarn.lock') }}-${{ env.XCODE_VERSION || 'default' }}
          restore-keys: |
            ${{ runner.os }}-detox-framework-

      - name: Clean and rebuild Detox framework cache
        if: steps.cache-detox-framework.outputs.cache-hit != 'true'
        run: |
          yarn detox clean-framework-cache
          yarn detox build-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build-${{ hashFiles('ios/Podfile.lock', 'package.json', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-detox-build-

      - name: Log cache status
        run: |
          if [[ "${{ steps.cache-detox-build.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit: Using cached ios/build"
          else
            echo "Cache miss: Building ios/build from scratch"
          fi

      - name: Start Metro bundler in background
        run: yarn start > metro.log 2>&1 &
        env:
          CI: true

      - name: Wait for Metro to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8081/status; then
              echo "Metro is up and running"
              exit 0
            fi
            sleep 1
          done
          echo "Error: Metro failed to start within 30 seconds"
          exit 1
        env:
          CI: true

      - name: Detox build
        run: |
          echo "Starting detox build at $(date)"
          yarn detox build --configuration ios.sim.debug
          echo "Finished detox build at $(date)"

      - name: Run Detox tests
        run: |
          echo "Starting detox tests at $(date)"
          detox test --configuration ios.sim.debug --loglevel verbose e2e/continueButton.test.js
          echo "Finished detox tests at $(date)"
        env:
          CI: true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: |
            artifacts
            metro.log
            ~/Library/Detox/ios/framework/
