name: Run Detox iOS Tests
on:
  workflow_dispatch:

jobs:
  detox-ios:
    name: iOS - Build and run Detox tests
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Install CocoaPods Dependencies
        run: cd ios && pod install

      - name: Build Detox for iOS
        run: npm run detox:ios:build

      - name: Start Metro Server
        run: npm run detox:start &

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox Tests on iOS
        run: npm run detox:ios:test:ci

      - name: Upload Test Artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-ios-artifacts
          path: artifacts
          retention-days: 5
